# Java Gradle Circle CI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/APPlugin
  docker:
    - image: circleci/android:api-27

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies || true

      - save_cache:
          paths:
            - .gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew test

      - store_artifacts:
          path: ./build/reports
          destination: reports

      - store_test_results:
          path: ./build/test-results

  deploy:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}

      - run:
          name: Build release package
          command: ./gradlew :ta_player_plugin:assembleRelease

      - run:
          name: Deploy to Bintray
          command: ./gradlew :ta_player_plugin:bintrayUpload

workflows:
  version: 2
  test-n-deploy:
    jobs:
      # Execute job for all branches, and all tags.
      - test:
          filters:
            tags:
              only: /.*/

      # Execute job for no branches, and all tags
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/





